### PR TITLE
changes for external db_file

### PR DESCRIPTION
**Pull request by babanomania**
With this change only external dependency on the docker image is the volume for db.sqlite3 file.
I've removed the dependency on docker-compose to mount the mysite directory, since it is available inside the docker image.

### CODE REVIEW

**Comment by DartLazer** [comment]
Hey thanks a lot!

It works except for the following:
In the command line for the docker-compose it should read:
`command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${WHOIH_PORT:-8000}"`
Instead of `python mysite/manage.py`

I'm not exactly sure what caused this but apparently because we removed the mysite mount the mounting dir is now different?

Your instructions were clear and it resulted in the DB file still being intact.

I'm not a docker wizard like you are so could you please eleborate what's going on here?
```bash 
docker container create --name dummy -v whoishomeui_dbstore:/mnt/test hello-world
docker cp mysite/db.sqlite3 dummy:/mnt/test/db.sqlite3
docker rm dummy
```
Am I correct in assuming we are creating a docker **container** with the name dummy and a **volume** whoishomeui_dbtstore.

We copy the files into the volume, and then we **only delete the container?** and the volume stays intact? Is that correct?

Thx!

**Comment by babanomania** [comment]
Ok I'll change the docker-compose accordingly

Regarding the upgrade instructions ,  it creates a dummy container , mounts the new drive on it, copies the file and then drops the container.

**Comment by babanomania** [comment]
@DartLazer please check the commits now

**Comment by DartLazer** [comment]
I think we are still mising the fixture (the preload) in this setup or am I wrong?

**Comment by DartLazer** [comment]
No problem.

I realized something else too @babanomania . By removing the `mysite` volume we introduced the situation where for every update, even textual, the user will have to rebuild the whole container.

Do you think it would be beneficial to leave the mysite volume in there too? Or does this have some drawbacks as well?

**Comment by babanomania** [comment]
@DartLazer ideally the mysite contents should be packed inside the docker image, in that way people can simple use the docker image inside their setup without referring to the code on github.

Whenever there is a version upgrade, you push a new image on docker-hub by increasing the version number.
I personally attach the WatchTower image to my docker-compose stack so that the container upgrades are handled automatically.

https://github.com/containrrr/watchtower

if we keep the mysite mounted from outside, automatic update feature is somewhat lost, they'll have to git pull from the github repo and then rerun the container.

**Comment by babanomania** [comment]
i've added changes for preloading of data, but not via json files this time.
The problem with using loadata and json file is every time the contaier is started, it might overrite the data.
I've now used the same strategy which was used for DiscordConfig model

@DartLazer you can check the commits now

**Comment by DartLazer** [comment]
> @DartLazer ideally the mysite contents should be packed inside the docker image, in that way people can simple use the docker image inside their setup without referring to the code on github.
> 
> 
> 
> Whenever there is a version upgrade, you push a new image on docker-hub by increasing the version number.
> 
> I personally attach the WatchTower image to my docker-compose stack so that the container upgrades are handled automatically.
> 
> 
> 
> https://github.com/containrrr/watchtower
> 
> 
> 
> if we keep the mysite mounted from outside, automatic update feature is somewhat lost, they'll have to git pull from the github repo and then rerun the container.

Amazing I've never done and heard of that before! Let's set this up on a beta / dev branch and test it! I'm very excited about that 😄

**Comment by DartLazer** [comment]
> i've added changes for preloading of data, but not via json files this time.
> 
> The problem with using loadata and json file is every time the contaier is started, it might overrite the data.
> 
> I've now used the same strategy which was used for DiscordConfig model
> 
> 
> 
> @DartLazer you can check the commits now

Thanks I'll have a look later today!

**Comment by babanomania** [comment]
> > i've added changes for preloading of data, but not via json files this time.
> > The problem with using loadata and json file is every time the contaier is started, it might overrite the data.
> > I've now used the same strategy which was used for DiscordConfig model
> > @DartLazer you can check the commits now
> 
> Thanks I'll have a look later today!
> 
> Edit: you're mentioning doing it via a migration? Is the migration file missing in the commit or is it just me haha

if you see this commit, you'll understand. I'm not really doing a migration
since it may insert a 2nd row in the table for existing users.

https://github.com/DartLazer/WhoIsHomeUI/commit/c6e26209313aad24d8c6996602e1a245f3628927

**Comment by DartLazer** [comment]
Ah yes I see interesting indeed. I think it should do for now clever idea. When i get back home from work I will test it!

**Comment by DartLazer** [comment]
@babanomania we could also use the django get_or_create method instead of the try except statement.  What do you think?

**Comment by DartLazer** [comment]
Okay I have merged into the dev branch! let's test it out

**Comment by DartLazer** [comment]
@babanomania Okay merge successful. I just deployed to my raspberry pi 4 and managed to migrate the database with your commands! Seems to be successful!

**Comment by babanomania** [comment]
@DartLazer check for new user also

**Pull request merged**
