### PR TITLE
Merging dev into main for the 0.3 upgrade.

### PR DESCRIPTION
**Pull request by DartLazer**
0.3 upgrade marks an important database change. Database wont be hosted in the mysite directory any longer but to a seperate docker volume.

Thanks to @babanomania for the hard work.

### CODE REVIEW

**Comment by spandan13** [comment]
@babanomania I am thinking of upgrading my prod. container from v0.17 to v0.3
Should a simple git pull and docker-compose up -d --build be enough or do I need to follow the other upgrade guide that is for v0.23 to v0.3??

**Comment by babanomania** [comment]
@spandan13 I'd suggest to follow the upgrade guide .
Also keep a copy of the db.sqlite3 file manually , just in case it is needed

**Comment by DartLazer** [comment]
> @babanomania I am thinking of upgrading my prod. container from v0.17 to v0.3
> Should a simple git pull and docker-compose up -d --build be enough or do I need to follow the other upgrade guide that is for v0.23 to v0.3??

Did you manage to upgrade?

**Comment by spandan13** [comment]
Yup done successfully!

**Pull request merged**
