### PR TITLE
Updated Docker-Compose for external DB, PORT and TimeZone

### PR DESCRIPTION
**Pull request by babanomania**
With this change the below can be changes via docker-compose

- Listen PORT
- TimeZone
- SQLite Docker Volume
-

### CODE REVIEW

**Review by DartLazer — COMMENTED** [review]
What are the changes to the html files and settings page about?

**Comment by DartLazer** [comment]
> What are the changes to the html files and settings page about? 

@babanomania

**Comment by babanomania** [comment]
I made a mistake, i was testing some UI changes in the settings page for using accordins and by mistake pushed it, 
please ignore this pull request. I'll create a fresh pull request without these changes

**Comment by DartLazer** [comment]
> I made a mistake, i was testing some UI changes in the settings page for using accordins and by mistake pushed it, 
> please ignore this pull request. I'll create a fresh pull request without these changes

No worries!  I'll wait for the pull request no rush!

**Pull request closed without merging**
